import type { Metadata } from "next";
import { AuthProvider } from "./context/AuthContext";
import FirestoreProvider from "./context/FireStoreContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Money Manager",
  description: "Generated by Juan Medina",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <AuthProvider>
        <FirestoreProvider>
          <body>{children}</body>
        </FirestoreProvider>
      </AuthProvider>
    </html>
  );
}
